# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: braccio_arm
  joint_model_group_pose: default
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - wrist_pitch_joint
    - wrist_roll_joint
    - gripper_joint
    - sub_gripper_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: braccio_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_joint
      - sub_gripper_joint
braccio_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - wrist_pitch_joint
    - wrist_roll_joint
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - gripper_joint
      - sub_gripper_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sub_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

