#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers
joint1_position_controller:
  type: effort_controllers/JointPositionController 
  joint: base_joint
  pid: {p: 700.0, i: 50, d: 70.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController 
  joint: shoulder_joint
  pid: {p: 700.0, i: 50, d: 70.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController 
  joint: elbow_joint
  pid: {p: 700.0, i: 50, d: 70.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController 
  joint: wrist_pitch_joint
  pid: {p: 700.0, i: 50, d: 70.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController 
  joint: wrist_roll_joint
  pid: {p: 700.0, i: 50, d: 70.0}
joint6_position_controller:
  type: effort_controllers/JointPositionController 
  joint: gripper_joint
  pid: {p: 700.0, i: 50, d: 70.0}
joint7_position_controller:
  type: effort_controllers/JointPositionController 
  joint: sub_gripper_joint
  pid: {p: 700.0, i: 50, d: 70.0}